; T1E Firmware — ESP-IDF on PlatformIO

[platformio]
src_dir = main

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv

[env:t1e-c3]
board = seeed_xiao_esp32c3
build_flags =
    -DBOARD_VARIANT_C3=1

[env:t1e-c6]
board = seeed_xiao_esp32c6
build_flags =
    -DBOARD_VARIANT_C6=0

;[env:t1e-c3-hello]
;board = seeed_xiao_esp32c3
;build_flags =
;    -DBOARD_VARIANT_C3=1
;    -DEPD_HELLO_TEST=1

;[env:t1e-c6-hello]
;board = seeed_xiao_esp32c6
;build_flags =
;    -DBOARD_VARIANT_C6=0
;    -DEPD_HELLO_TEST=1
